events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /products {
            proxy_pass http://product-service:5002/products;
        }

        location /orders {
            proxy_pass http://order-service:5003/orders;
        }

        location /payments {
            proxy_pass http://payment-service:5004/payments;
        }

        location /notifications {
            proxy_pass http://notification-service:5005/notifications;
        }

        location /reviews {
            proxy_pass http://review-service:5006/reviews;
        }

        location /login {
            proxy_pass http://auth-service:5001/login;
        }

        location /register {
            proxy_pass http://auth-service:5001/register;
        }

        location /auth-health {
            proxy_pass http://auth-service:5001/health;
        }

        location /product-health {
            proxy_pass http://product-service:5002/health;
        }

        location /order-health {
            proxy_pass http://order-service:5003/health;
        }

        location /payment-health {
            proxy_pass http://payment-service:5004/health;
        }

        location /notification-health {
            proxy_pass http://notification-service:5005/health;
        }

        location /review-health {
            proxy_pass http://review-service:5006/health;
        }
    }
}